#!/usr/bin/env python3
"""
Upsert one briefing snapshot into Supabase.

Called by the scheduled Claude task (morning/evening brief) after it has
gathered and sorted the day's content into a JSON payload matching the shape
the frontend (web/modules/morning-brief/module.js) expects. This script does
the actual network write; Claude's own gather/sort/write reasoning stays in
the schedule instructions, not here.

Usage:
    SUPABASE_URL=https://xxxx.supabase.co \
    SUPABASE_SERVICE_ROLE_KEY=eyJ... \
    python3 push_snapshot.py --kind morning --date 2026-07-19 --payload-file brief.json

The service_role key bypasses Row Level Security, which is why it must
never be committed to the repo or exposed to the browser -- it only ever
lives in an environment variable at push time.

Encryption: if any device has registered a key in public.encryption_keys
(see web/shell/crypto.js), the payload is encrypted once per active
device -- via ECDH P-256 + HKDF-SHA256 + AES-256-GCM, requires the
`cryptography` package (pip install cryptography) -- and written to
payload_encrypted instead of the plaintext payload column, so Supabase
itself never sees the sensitive email/calendar-derived content in the
clear. Before any device has registered, this falls back to plaintext so
first-time setup still works; once at least one device is registered, it
always encrypts (an encryption failure at that point is a hard error, not
a silent plaintext fallback -- that would defeat the whole point).
"""

import argparse
import base64
import json
import os
import re
import secrets
import sys
import urllib.request
import urllib.error

# Mirrors the isSafeSvg() allowlist in web/shell/svg-sanitize.js, which
# renders payload.svg via innerHTML. The svg field is meant to be pure
# geometry generated by the scheduled task's own reasoning, never raw
# calendar/email text -- but that reasoning processes untrusted third-party
# content, so this check rejects the push outright (rather than let a bad
# row reach Supabase at all) if the svg field ever contains an unrecognized
# tag, event handler, href, or embedded script/comment. Runs on the
# plaintext payload, before any encryption below.
_SVG_ALLOWED_TAGS = {
    "svg", "g", "path", "circle", "ellipse", "line", "polyline", "polygon",
    "rect", "text", "tspan", "defs", "lineargradient", "radialgradient", "stop",
}


def is_safe_svg(svg) -> bool:
    if not isinstance(svg, str) or len(svg) > 20000:
        return False
    if not re.match(r"^\s*<svg[\s>]", svg, re.I) or not re.search(r"</svg>\s*$", svg, re.I):
        return False
    if re.search(r"<!--|<!\[CDATA\[|<\?", svg):
        return False
    tags = re.findall(r"</?([a-zA-Z][\w:-]*)", svg)
    if any(t.lower() not in _SVG_ALLOWED_TAGS for t in tags):
        return False
    if re.search(r"\son[a-z]+\s*=", svg, re.I) or re.search(r"\bhref\s*=", svg, re.I):
        return False
    if re.search(r"javascript:", svg, re.I):
        return False
    return True


def supabase_request(supabase_url, service_key, path, method="GET", body=None, extra_headers=None):
    url = f"{supabase_url.rstrip('/')}{path}"
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("apikey", service_key)
    req.add_header("Authorization", f"Bearer {service_key}")
    req.add_header("Content-Type", "application/json")
    for k, v in (extra_headers or {}).items():
        req.add_header(k, v)
    with urllib.request.urlopen(req) as resp:
        raw = resp.read()
        return json.loads(raw) if raw else None


def fetch_active_keys(supabase_url, service_key):
    return supabase_request(
        supabase_url, service_key,
        "/rest/v1/encryption_keys?select=id,public_key_jwk&active=eq.true",
    ) or []


def _b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def encrypt_for_device(payload_dict, key_id, jwk):
    # Imported lazily so the script can still run (and hit the
    # no-keys-registered fallback path) on a machine that hasn't installed
    # `cryptography` yet, as long as no device has enrolled.
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.kdf.hkdf import HKDF
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    from cryptography.hazmat.primitives import hashes

    def b64url_to_int(s: str) -> int:
        pad = "=" * (-len(s) % 4)
        return int.from_bytes(base64.urlsafe_b64decode(s + pad), "big")

    def int_to_b64url(n: int, length: int = 32) -> str:
        return base64.urlsafe_b64encode(n.to_bytes(length, "big")).decode("ascii").rstrip("=")

    recipient_pub = ec.EllipticCurvePublicNumbers(
        b64url_to_int(jwk["x"]), b64url_to_int(jwk["y"]), ec.SECP256R1(),
    ).public_key()

    ephemeral_priv = ec.generate_private_key(ec.SECP256R1())
    shared_secret = ephemeral_priv.exchange(ec.ECDH(), recipient_pub)
    aes_key = HKDF(
        algorithm=hashes.SHA256(), length=32, salt=bytes(32), info=b"tor-dash-envelope-v1",
    ).derive(shared_secret)

    iv = secrets.token_bytes(12)
    ciphertext = AESGCM(aes_key).encrypt(iv, json.dumps(payload_dict).encode("utf-8"), None)

    epk_numbers = ephemeral_priv.public_key().public_numbers()
    return {
        "v": 1,
        "alg": "ECDH-P256+HKDF-SHA256+AES-256-GCM",
        "key_id": key_id,
        "epk": {
            "kty": "EC", "crv": "P-256",
            "x": int_to_b64url(epk_numbers.x), "y": int_to_b64url(epk_numbers.y),
        },
        "iv": _b64(iv),
        "ciphertext": _b64(ciphertext),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kind", required=True, choices=["morning", "evening"])
    parser.add_argument("--date", required=True, help="YYYY-MM-DD, the for_date column")
    parser.add_argument("--payload-file", required=True, help="Path to a JSON file with the brief payload")
    args = parser.parse_args()

    supabase_url = os.environ.get("SUPABASE_URL")
    service_key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if not supabase_url or not service_key:
        print("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in the environment.", file=sys.stderr)
        sys.exit(1)

    with open(args.payload_file, "r", encoding="utf-8") as f:
        payload = json.load(f)

    if "svg" in payload and payload["svg"] and not is_safe_svg(payload["svg"]):
        print(
            "Refusing to push: payload.svg failed the safety allowlist check "
            "(unrecognized tag, event handler, href, or embedded script/comment).",
            file=sys.stderr,
        )
        sys.exit(1)

    row = {"kind": args.kind, "for_date": args.date}

    try:
        keys = fetch_active_keys(supabase_url, service_key)
    except (urllib.error.HTTPError, urllib.error.URLError) as e:
        print(f"Couldn't fetch registered devices from encryption_keys: {e}", file=sys.stderr)
        sys.exit(1)

    if not keys:
        print("No devices have registered an encryption key yet -- pushing this snapshot in plaintext. "
              "Register a device from the dashboard's Security panel to start encrypting.", file=sys.stderr)
        row["payload"] = payload
        row["payload_encrypted"] = None
    else:
        try:
            envelopes = [encrypt_for_device(payload, k["id"], k["public_key_jwk"]) for k in keys]
        except ModuleNotFoundError:
            print(
                "The `cryptography` package is required to encrypt for the registered device(s) "
                "(pip install cryptography). Refusing to push in plaintext now that a device is enrolled.",
                file=sys.stderr,
            )
            sys.exit(1)
        row["payload"] = None
        row["payload_encrypted"] = envelopes

    try:
        supabase_request(
            supabase_url, service_key,
            "/rest/v1/briefing_snapshots?on_conflict=kind,for_date",
            method="POST", body=[row],
            extra_headers={"Prefer": "resolution=merge-duplicates,return=minimal"},
        )
        mode = "plaintext" if not keys else f"encrypted for {len(keys)} device(s)"
        print(f"OK: {args.kind} snapshot for {args.date} pushed ({mode}).")
    except urllib.error.HTTPError as e:
        print(f"Supabase rejected the write ({e.code}): {e.read().decode('utf-8', 'replace')}", file=sys.stderr)
        sys.exit(1)
    except urllib.error.URLError as e:
        print(
            "Could not reach Supabase. If this is a Claude scheduled task, "
            "make sure the project's *.supabase.co domain is added under "
            f"Settings -> Capabilities (network allowlist). Details: {e}",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
